name: deployAnsibleGCP

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout my repo
      uses: actions/checkout@v3

    - name: print current working directory
      run: |
        pwd
    - name: list directory contents
      run: |
        ls -lart
    - name: list directory contents of directory one level up
      run: |
        cd ..
        ls -lart
    - name: Set up GCP credentials
      uses: google-github-actions/setup-gcloud@master
      with:
        project_id: ${{ secrets.gcp_project_id }}
        service_account_key: ${{ secrets.gcp_credentials }}
    - name: Run playbook
      uses: dawidd6/action-ansible-playbook@v2
      env:
        region: ${{ vars.region }}
        ssh_public_key: ${{ secrets.ssh_public_key }}
      with:
        service_account_key: ${{ secrets.gcp_credentials }}
        playbook: ansible/deploy-gcp.yml
        options: |
          --verbose
